/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.isu.cs2263.hw01;



import org.apache.commons.cli.*;

import jdk.internal.joptsimple.HelpFormatter;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;




public class App {
    

    public static void main(String[] args)  {

        Options options = createOptions();
        
        CommandLineParser parser = new DefaultParser();

        try {
            CommandLine cmd = parser.parse(options, args); 
            if(cmd.hasOption("help")){
                printHelpMessage(options);
                System.exit(0);
            } 
            } catch (ParseException e) {
                System.err.println("Failed to parse: " + e.getMessage());
       
             }
        
    }

    private static Options createOptions(){
        Options options = new Options();
        Option helpOption = Option.builder("h").longOpt("help").desc("Print usage message.").build();
        Option batchOption = Option.builder("b").longOpt("batch").argName("file").hasArg().desc("Batch file that has expressions to evaluate").build();
        Option outputOption = Option.builder("o").longOpt("output").argName("file").hasArg().desc("Output File").build();

        options.addOption(helpOption);
        options.addOption(batchOption);
        options.addOption(outputOption);
        return options;
    }
    
    private static void printHelpMessage(Options options){
        HelpFormatter formatter = new HelpFormatter();
        formatter.printHelp("eval [OPTIONS]", "Evaluation of simple mathematical expressions\n\n", options);
        }
}
